name: obsidian_dart
description: A multipurpose discord bot.
version: 2.0.0
homepage: https://dhzdhd.github.io/Obsidian/

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
dependencies:
  dio: ^4.0.6
  dotenv: ^4.0.1
  http: ^0.13.4
  nyxx: ^3.4.2
  nyxx_extensions: ^3.0.0
  nyxx_interactions: ^4.2.1
  nyxx_lavalink: ^3.0.1
  math_expressions: ^2.2.0
  supabase: ^0.3.5
